Fixing the below deprecations.
Error: The `Layout/AlignArguments` cop has been renamed to `Layout/ArgumentAlignment`.
(obsolete configuration found in .rubocop-https---gitlab-com-bsm-misc-raw-master-rubocop-default-yml, please update it)
The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in .rubocop-https---gitlab-com-bsm-misc-raw-master-rubocop-default-yml, please update it)
The `Layout/AlignParameters` cop has been renamed to `Layout/ParameterAlignment`.
(obsolete configuration found in .rubocop-https---gitlab-com-bsm-misc-raw-master-rubocop-default-yml, please update it)
The `Layout/IndentFirstArrayElement` cop has been renamed to `Layout/FirstArrayElementIndentation`.
(obsolete configuration found in .rubocop-https---gitlab-com-bsm-misc-raw-master-rubocop-default-yml, please update it)